services:
  database:
    image: postgres:16
    hostname: ${POSTGRES_HOST}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:${POSTGRES_PORT}"
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    build: backend
    ports:
      - "8000:${SITE_PORT}"
    env_file:
      - .env
    depends_on:
      - database
    tty: true
    volumes:
      - .:/app

volumes:
  db:
