# Generated by Django 4.2.11 on 2024-07-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resettoken',
            options={'verbose_name': 'Reset Token'},
        ),
        migrations.AddIndex(
            model_name='resettoken',
            index=models.Index(fields=['user'], name='reset_token_user_index'),
        ),
        migrations.AlterModelTable(
            name='resettoken',
            table='reset_token',
        ),
    ]
