# Generated by Django 4.2.11 on 2024-06-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bookinstance',
            name='book_instance_due_date_index',
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('B', 'Borrowed'), ('R', 'Reserved'), ('A', 'Available')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AddIndex(
            model_name='bookinstance',
            index=models.Index(fields=['book', 'status', 'borrower'], name='book_instance_book_index'),
        ),
        migrations.AddConstraint(
            model_name='bookinstance',
            constraint=models.UniqueConstraint(models.F('book'), models.F('borrower'), name='book_instance_unique_book_borrower'),
        ),
    ]
