# Generated by Django 4.2.11 on 2024-04-28 14:20

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import library_system.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', '-publish_date']},
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_date']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateField(default=datetime.date(2024, 4, 28)),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Value must be positive.')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 character ISBN number.', max_length=13, unique=True, validators=[library_system.validators.ISBNValidator], verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Value must be positive.')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(help_text="A short summary of the book's story."),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 19), help_text='Date that the borrower must return the book by. Defaults to 3 weeks after borrowing.', null=True),
        ),
    ]
