# Generated by Django 4.2.11 on 2024-04-28 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_system', '0002_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Value must be positive.')]),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_date',
            field=models.DateField(blank=True, help_text='Date that the borrower must return the book by. Defaults to 3 weeks after borrowing.', null=True),
        ),
    ]
