# Generated by Django 4.2.11 on 2024-06-30 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_system', '0002_remove_bookinstance_book_instance_due_date_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveIndex(
            model_name='bookinstance',
            name='book_instance_book_index',
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Available'), ('B', 'Borrowed')], default='A', max_length=1),
        ),
        migrations.AddIndex(
            model_name='bookinstance',
            index=models.Index(fields=['status', 'book'], name='b-instance_status_book_index'),
        ),
        migrations.AddIndex(
            model_name='bookinstance',
            index=models.Index(fields=['book', 'borrower'], name='b-instance_book_borrower_index'),
        ),
        migrations.AddField(
            model_name='bookreservation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='library_system.book'),
        ),
        migrations.AddField(
            model_name='bookreservation',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bookreservation',
            index=models.Index(fields=['id', 'book'], name='b-reservation_id_book'),
        ),
    ]
