# Generated by Django 4.2.11 on 2024-05-02 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_system', '0003_alter_book_edition_alter_bookinstance_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Value must be positive.')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(),
        ),
    ]
